# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: formats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='formats.proto',
  package='isg_ai',
  syntax='proto2',
  serialized_pb=_b('\n\rformats.proto\x12\x06isg_ai\"\x9b\x01\n\x16ImageNumberNumberTuple\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x13\n\x0btrain_label\x18\x05 \x01(\x05\x12\x12\n\ntrue_label\x18\x06 \x01(\x05\x12\x10\n\x08img_type\x18\x07 \x01(\t')
)




_IMAGENUMBERNUMBERTUPLE = _descriptor.Descriptor(
  name='ImageNumberNumberTuple',
  full_name='isg_ai.ImageNumberNumberTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageNumberNumberTuple.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageNumberNumberTuple.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageNumberNumberTuple.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageNumberNumberTuple.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_label', full_name='isg_ai.ImageNumberNumberTuple.train_label', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='true_label', full_name='isg_ai.ImageNumberNumberTuple.true_label', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_type', full_name='isg_ai.ImageNumberNumberTuple.img_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['ImageNumberNumberTuple'] = _IMAGENUMBERNUMBERTUPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageNumberNumberTuple = _reflection.GeneratedProtocolMessageType('ImageNumberNumberTuple', (_message.Message,), dict(
  DESCRIPTOR = _IMAGENUMBERNUMBERTUPLE,
  __module__ = 'formats_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageNumberNumberTuple)
  ))
_sym_db.RegisterMessage(ImageNumberNumberTuple)


# @@protoc_insertion_point(module_scope)
